Adding Heart Shape
catdad/canvas-confetti pull request #193
Opened 2023-01-26 01:09 UTC by hjardines

Getting ready for Valentine's Day.

Thanks for all the hard work.

2023-09-16 08:57 UTC, fenilmodi00 approved these changes

2023-09-16 08:57 UTC, fenilmodi00 approved these changes

2023-09-28 02:49 UTC, catdad requested changes

2023-10-03 21:34 UTC, closed without merging

2023-10-03 21:34 UTC, catdad commented
I am closing this PR in favor of #203. The new custom shapes support wobbling and rendering flat and are fully scalable. There is a heart available in the example that was included in that PR. It has been shipped in version 1.8.0.